AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for React frontend + API + DynamoDB + 6 Lambdas

Resources:
  # API Gateway Rest API (SAM will auto-create it)
  RollWithIt: 
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: RollWithIt

  # Lambda functions (6 total)
  createPackingList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createPackingList
      Handler: index.handler
      Runtime: nodejs22.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: roll_with_it
      CodeUri: ./src/createPackingList/
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref RollWithIt
            Path: /src/createPackingList
            Method: post

  addToPackingList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: addToPackingList
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: ./src/addToPackingList/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: roll_with_it
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref RollWithIt
            Path: /src/addToPackingList
            Method: post

  getAllPackingLists:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getAllPackingLists
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: ./src/getAllPackingLists/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: roll_with_it
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref RollWithIt
            Path: /src/getAllPackingLists
            Method: get

  getPackingList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getPackingList
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: ./src/getPackingList/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: roll_with_it
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref RollWithIt
            Path: /src/getPackingList
            Method: get

  updatePackingList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updatePackingList
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: ./src/updatePackingList/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: roll_with_it
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /src/updatePackingList
            Method: post
            ApiId: !Ref RollWithIt

  updatePackingListItem:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updatePackingListItem
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: ./src/updatePackingListItem/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: roll_with_it
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref RollWithIt
            Path: /updatePackingListItem
            Method: post

Outputs:
  ApiUrl:
    Description: "HTTP API endpoint base URL"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/"